db:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/shiro?serverTimezone=UTC
  username: root
  password: 123456
hibernate:
  show_sql: true
  format_sql: true
  ejb.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  hbm2ddl.auto: update
packages.to.scan: com.sh.shdemo.entity
spring:
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      password: 123
      name: user
#  resources:
#    static-locations: /static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  servlet:
    multipart:
      max-file-size: 20MB
  freemarker:
    request-context-attribute: request
    suffix: .ftl
    expose-session-attributes: true
    expose-request-attributes: true
    content-type: text/html
    check-template-location: true
    charset: UTF-8
    cache: false
    template-loader-path: classpath:/templates
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000
    database: 0
    pool:
      max-active: 10
      max-idle: 8
      min-idle: 0
      max-wait: -1
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
